[package]
name = "ux-animate"
version = "0.1.0"
authors = ["Victor Dudochkin <dudochkin.victor@gmail.com>"]
readme = "README.md"
homepage = "https://angular-rust.github.io/ux-animate"
repository = "https://github.com/angular-rust/ux-animate"
documentation = "https://docs.rs/ux-animate"
description = "Backend and runtime agnostic animation library"
keywords = ["wasm", "web", "webassembly", "awesome", "graphics", "gtk", "cairo"]
categories = ["multimedia", "wasm", "web-programming", "gui"]
edition = "2018"
license = "MPL-2.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
web = ["wasm-bindgen", "wasm-bindgen-futures", "wasm-logger", "gloo", "js-sys", "wasm-bindgen-test", "web-sys"]
cairo = ["cairo-rs", "png", "gio", "gtk"]
default = ["cairo"]

[dependencies]
log = "0.4"
ux-primitives = { git = "https://github.com/angular-rust/ux-primitives.git" }

png = { version = "0.16", optional = true }
gio = { version = "0.9", features = ["v2_58"], optional = true }
gtk = { version = "0.9", features = ["v3_22"], optional = true }
cairo-rs = { version = "0.9", features = ["png"], optional = true }

wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm-logger = { version = "0.2", optional = true }
gloo = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
wasm-bindgen-test = { version = "0.3", optional = true }
serde = "1.0.123"
serde_json = "1.0.62"

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
  'KeyboardEvent',
  "ValidityState",
  "CustomEvent",
  "Node",
  "Element",
  "HtmlElement",
  "Window",
  "Document",
  "CanvasRenderingContext2d",
  "HtmlCanvasElement"
]

[dev-dependencies]


# [[example]]
# name = "web-example"
# # crate-type = ["staticlib"]
# required-features = ["web"]

[[example]]
name = "cairo-example"
required-features = ["cairo"]
